# Generated by Django 4.0.2 on 2022-02-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='z',
            field=models.FloatField(),
        ),
    ]
