# Generated by Django 4.0.2 on 2022-02-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0002_alter_reading_x_alter_reading_y_alter_reading_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
    ]
