# Generated by Django 4.0.2 on 2022-02-26 02:58

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0003_alter_session_endtime'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.CheckConstraint(check=models.Q(('x__gte', 0), ('x__lte', 10), ('y__gte', 0), ('y__lte', 10), ('z__gte', 0), ('z__lte', 10)), name='location_bounds_check'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('session', 't'), name='idempotency_check'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(('startTime__lte', django.db.models.expressions.F('endTime'))), name='session_startTime_before_endTime_check'),
        ),
    ]
