# Generated by Django 4.0.2 on 2022-02-26 13:56

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0003_alter_session_endtime'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.CheckConstraint(check=models.Q(('quality__gte', 0), ('quality__lte', 100)), name='quality_bounds_check'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('session', 't'), name='idempotency_check'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(('startTime__lte', django.db.models.expressions.F('endTime'))), name='session_startTime_before_endTime_check'),
        ),
    ]
