# Generated by Django 4.0.2 on 2022-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0004_reading_quality_bounds_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('key', models.CharField(max_length=100,
                 primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
