# Generated by Django 4.0.2 on 2022-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0004_reading_location_bounds_check_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.CheckConstraint(check=models.Q(('quality__gte', 0), ('quality__lte', 100)), name='quality_bounds_check'),
        ),
    ]
