# Generated by Django 4.0.2 on 2022-03-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0005_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('hardwareId', models.CharField(max_length=200)),
                ('metadata', models.CharField(
                    blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='metadata',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='device',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='exhibitionInferenceApp.device'),
        ),
    ]
