# Generated by Django 4.0.2 on 2022-03-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitionInferenceApp', '0006_device_session_metadata_alter_session_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='hardwareId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='device',
            field=models.ForeignKey(db_column='hardwareId', on_delete=django.db.models.deletion.CASCADE, to='exhibitionInferenceApp.device'),
        ),
    ]
