"""
Django settings for exhibitionInferenceSite project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import subprocess

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q^$k*hr0v1msc*7hz+k-v5eyg@&4avfijms3gnx!a1%%qng(@="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# get site-local IP of host
# To ensure same output as hostname -I, subprocess is used instead of socket.gethostbyname(socket.gethostname()).
# Pi's /etc/host has a 127.0.1.1 -> raspberryPi entry, which messes socket.gethostbyname command up to return 127.0.0.1
# instead of the site-local IP address.
ALLOWED_HOSTS = subprocess.run(["hostname", "-I"], capture_output=True)\
    .stdout.decode().strip().split(' ')


# Application definition

INSTALLED_APPS = [
    "exhibitionInferenceApp.apps.ExhibitionInferenceAppConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "exhibitionInferenceSite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "exhibitionInferenceSite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Django will resolve static URLs to have this prefix.
# Need to make sure Nginx serves the files at the same prefix.
# so in nginx.conf:
# location /<static url>/ { ... }
# <static url> must be equal to whatever STATIC_URL here is (without the trailing /)
STATIC_URL = "static/"

# Where static files served by Nginx reside
STATIC_ROOT = BASE_DIR / "static_root/"

# for (python3 manage.py collectstatic) to find static files not defined inside exhibitionInferenceApp/
STATICFILES_DIRS = [
    BASE_DIR / "cssBootstrap",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
